### ISSUE TITLE
API rate limiting breaks git-clone-fork

### ISSUE THREAD

**Issue by dhellmann** [stbenjam/git-clone-fork#3]
I tried `git clone-fork dhellmann/hive` and received:

```
GET https://api.github.com/repos/dhellmann/hive: 403 API rate limit exceeded for 
<my IP here>. (But here's the good news: Authenticated requests get a higher rate limit. 
Check out the documentation for more details.) [rate reset in 7m51s]
```

It would be nice if the API client used the authentication token from my ~/.gitconfig file.

**Comment by stbenjam** [comment]
Thanks, good idea - in my own testing I wasn't making enough queries to get throttled. Would you mind trying https://github.com/stbenjam/git-clone-fork/pull/4?
